export const listings = [
  {
    id: 1,
    slug: 'cliffside-villa-cascais',
    mode: 'rent',
    type: 'Villa',
    location: 'Cascais, Portugal',
    title: 'Cliffside Villa in Cascais',
    description: 'A calm coastal retreat with Atlantic views, native gardens and a sun-washed infinity pool.',
    price: '€7,500 / month',
    beds: 4,
    baths: 4,
    size: '320 m²',
    image: '/assets/listing-cascais.jpg',
  },
  {
    id: 2,
    slug: 'kensington-garden-house',
    mode: 'rent',
    type: 'Townhouse',
    location: 'London, United Kingdom',
    title: 'Kensington Garden House',
    description: 'A composed family home pairing period proportions with a private planted courtyard.',
    price: '£7,000 / month',
    beds: 4,
    baths: 3,
    size: '265 m²',
    image: '/assets/listing-kensington.jpg',
  },
  {
    id: 3,
    slug: 'chelsea-gallery-apartment',
    mode: 'buy',
    type: 'Apartment',
    location: 'London, United Kingdom',
    title: 'Chelsea Gallery Apartment',
    description: 'Quiet lateral living with considered joinery, gallery walls and south-facing light.',
    price: '£1,800,000',
    beds: 2,
    baths: 2,
    size: '124 m²',
    image: '/assets/listing-chelsea.jpg',
  },
  {
    id: 4,
    slug: 'modern-villa-mallorca',
    mode: 'buy',
    type: 'Villa',
    location: 'Mallorca, Spain',
    title: 'Modern Villa in Mallorca',
    description: 'Stone, oak and open sky shape this peaceful Tramuntana home above the olive groves.',
    price: '€3,250,000',
    beds: 5,
    baths: 5,
    size: '410 m²',
    image: '/assets/listing-mallorca.jpg',
  },
  {
    id: 5,
    slug: 'waterfront-residence-dublin',
    mode: 'buy',
    type: 'House',
    location: 'Dublin, Ireland',
    title: 'Waterfront Residence in Dublin',
    description: 'A precise contemporary home with sheltered terraces and uninterrupted bay views.',
    price: '€2,450,000',
    beds: 4,
    baths: 3,
    size: '286 m²',
    image: '/assets/listing-dublin.jpg',
  },
  {
    id: 6,
    slug: 'eixample-penthouse-barcelona',
    mode: 'buy',
    type: 'Penthouse',
    location: 'Barcelona, Spain',
    title: 'Eixample Penthouse',
    description: 'An elegant top-floor home with a wraparound terrace and views across the city grid.',
    price: '€2,100,000',
    beds: 3,
    baths: 3,
    size: '198 m²',
    image: '/assets/listing-barcelona.jpg',
  },
];

export const testimonials = [
  {
    quote: 'They listened for the details we had not found words for yet. Every home on the shortlist felt genuinely relevant.',
    name: 'Clara M.',
    context: 'Buyer, Mallorca',
  },
  {
    quote: 'Our search moved across two countries and still felt uncomplicated. The advice was measured, clear and never rushed.',
    name: 'Julian R.',
    context: 'Buyer, Lisbon',
  },
  {
    quote: 'The remote viewings were exceptionally thorough. By the time we arrived, we already knew which home felt right.',
    name: 'Amelia K.',
    context: 'Tenant, London',
  },
  {
    quote: 'From first conversation to final handover, we always knew what would happen next and who was handling it.',
    name: 'Matteo S.',
    context: 'Seller, Barcelona',
  },
  {
    quote: 'Their local knowledge saved us months. More importantly, they understood the pace and privacy our family needed.',
    name: 'Nora B.',
    context: 'Buyer, Cascais',
  },
  {
    quote: 'Thoughtful, candid and entirely on our side. It was the first property experience that felt truly personal.',
    name: 'Daniel T.',
    context: 'Buyer, Dublin',
  },
];

export const faqs = [
  {
    question: 'What is the buying process?',
    answer: 'We begin with a private briefing, curate a focused shortlist and arrange viewings. Once you choose a home, we coordinate negotiation, local due diligence, contracts and handover with your advisers.',
  },
  {
    question: 'What are the costs?',
    answer: 'Acquisition costs vary by market and property. Before a viewing programme begins, we provide a clear estimate covering local taxes, legal fees, surveys and any agency costs.',
  },
  {
    question: 'What makes the service different?',
    answer: 'We work with a small number of clients and assess every home personally. The result is a shorter, more relevant search supported by candid local advice.',
  },
  {
    question: 'How can I schedule a viewing?',
    answer: 'Select a property or send us your brief. We can arrange a private in-person appointment or a live guided video tour at a time that works across time zones.',
  },
  {
    question: 'Do you work with international buyers?',
    answer: 'Yes. We regularly coordinate cross-border searches and can introduce trusted legal, tax, finance and relocation specialists in each market.',
  },
];
